version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - payment-network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - payment-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - payment-network

  gateway:
    build:
      context: .
      dockerfile: ./docker/gateway.Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - rabbitmq
      - auth-service
      - user-service
      - payment-service
      - transaction-service
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - payment-network

  auth-service:
    build:
      context: .
      dockerfile: ./docker/auth-service.Dockerfile
      target: development
    command: pnpm run start:dev auth-service
    env_file:
      - ./apps/auth-service/.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - payment-network

  user-service:
    build:
      context: .
      dockerfile: ./docker/user-service.Dockerfile
      target: development
    command: pnpm run start:dev user-service
    env_file:
      - ./apps/user-service/.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - payment-network

  payment-service:
    build:
      context: .
      dockerfile: ./docker/payment-service.Dockerfile
      target: development
    command: pnpm run start:dev payment-service
    env_file:
      - ./apps/payment-service/.env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - payment-network

  transaction-service:
    build:
      context: .
      dockerfile: ./docker/transaction-service.Dockerfile
      target: development
    command: pnpm run start:dev transaction-service
    env_file:
      - ./apps/transaction-service/.env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - payment-network

  notification-service:
    container_name: notification-service
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - 3002:3002

networks:
  payment-network:
    driver: bridge

volumes:
  postgres:
  mongodb_data:
